### ISSUE TITLE
cannot build the solution after extracting the downloaded zip file..

### ISSUE THREAD

**Issue by gian-te** [2gis/Winium.StoreApps.CodedUi#28]
I downloaded the Winium.StoreApps.CodedUi-master zip file and extracted it. Opening the solution gives me this (I am using Visual Studio 2013 premium on a windows 8.1 machine) : 
![image](https://cloud.githubusercontent.com/assets/22191379/18510580/5b38d9b0-7ab1-11e6-8452-0ac081be6772.png)

Also after opening the sln file, i cannot find the referenced projects (I have installed the sdk from https://developer.microsoft.com/en-us/windows/downloads/sdk-archive):
![image](https://cloud.githubusercontent.com/assets/22191379/18510618/978a4e80-7ab1-11e6-9b9e-7be0719c36bd.png)

**Comment by gian-te** [comment]
![image](https://cloud.githubusercontent.com/assets/22191379/18510745/479d0600-7ab2-11e6-88f2-28a901f8d113.png)

I apologize if the issue is easy to fix, I am fairly new to developing software when using external projects..

**Comment by NickAb** [comment]
Are you sure that you are running Premium version? Could you please provide full VS version, including any Update. This information can be found "Help -> About Microsoft Visual Studio". We used VS 2013 Premium Update 5.

Missing references and incompatibility with StoreApps project might suggest that you don't have necessary SDK installed. Do you have Windows Phone SDK?

Missing reference should be fixed after installing Windows Phone 8.1 SDK.
Missing references can be found in `C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.1\Tools\AppDeploy` or
`C:\Program Files (x86)\Microsoft XDE\8.1\`, or in GAC (`C:\WINDOWS\Microsoft.Net\assembly\GAC_32`). Even after installing dependencies you might need to manually specify path to each broken reference, because Visual Studio sometimes changes path to broken references. You can repair them manually or delete files and unpack solution again, so that you have clean install. Or, instead of zip, you can clone repository and use working copy, that way you will always know what have changed by running `git status`.

**Comment by gian-te** [comment]
Yes, I am sure that I have vs2013 premium but I am just currently updating to Update 5. Maybe that's the reason why it says incompatible.. I will get back to you when I get back to work if this fixed the incompatibility issue.

As for the SDK, I will get back to you as soon as I can because I do not remember if it was v8.1 or v8.0.. I will give an update as soon as I can and thank you for the response.

**Comment by gian-te** [comment]
It turns out that the update was all I needed. deleted the files then unpacked the zip after downloading Update 5. Opening the solution after updating doesn't give me the incompatibility error anymore.  Thanks for this!

**Comment by gian-te** [comment]
Hi I've encountered an error in the Do() method in CommandExecutorBase clas
saying:

![image](https://cloud.githubusercontent.com/assets/22191379/18545775/29ab5c44-7b6d-11e6-94f7-36be76921867.png)

I am attempting to push/install a .xap file to the windows phone. This xap file is the app that i will run tests on from my team's automation framework. I am encountering the said error in this line of code in the Driver.
![image](https://cloud.githubusercontent.com/assets/22191379/18545866/a36146ca-7b6d-11e6-8bef-b308f57e5815.png)

I am able to break point on your code by spawning a remoteWebDriver with C# using this line of code on our team's framework:
AutoDriver = new RemoteWebDriver(new Uri(mobileDevice.MobileUrl), capabilities);
where mobile url is "http://127.0.0.1:9999".
